# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

before_install:
  - cd rlogic

r:
# - 3.1 # tidyselect requires 3.2
- 3.2
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'
